version: "3.9"

services:

  postgres:
    image: postgres:17-alpine
    container_name: billing-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing_user_db

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - billing-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    container_name: user-service

    build:
      context: .
      dockerfile: user-service/Dockerfile

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - ./user-service/.env

    ports:
      - "3002:3002"

    networks:
      - billing-network

  api-gateway:
    container_name: api-gateway

    build:
      context: .
      dockerfile: api-gateway/Dockerfile

    restart: unless-stopped

    depends_on:
      - user-service

    env_file:
      - ./api-gateway/.env

    ports:
      - "3000:3000"

    networks:
      - billing-network

networks:
  billing-network:

volumes:
  postgres-data: