version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: billing_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billing_user_dev
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    container_name: user_service
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    env_file:
      - ./user-service/.env

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    depends_on:
      - user-service
    ports:
      - "5000:5000"
    env_file:
      - ./api-gateway/.env